# Generated by Django 2.1.15 on 2020-06-09 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Creating_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Creating_Date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankData.User'),
        ),
    ]
