# Generated by Django 3.1a1 on 2020-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_more', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_more',
            name='Address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_more',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_more',
            name='Company',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_more',
            name='Creating_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_more',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_more',
            name='Status',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_more',
            name='Surname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
